build:
  nodes:
    coverage:
      tests:
        override:
          - js-scruitinizer-run
          - command: npm test
            coverage:
              file: coverage/clover.xml
              format: clover
